### PR TITLE
Make it easier to extend TileProvider

### PR DESCRIPTION
**Pull request by kengu**
CustomTileProvider only gives allows for custom url-scheme. This PR make it possible to extend TileProvider to make your own TileProvider implementations without the use of internal apis.

### CODE REVIEW

**Comment by kengu** [comment]
Sure @johnpryan, I'll lokk into it shortly

**Comment by kengu** [comment]
There, @johnpryan - all done.

**Comment by johnpryan** [comment]
Can you double check if these changes are correct? I don't see any changes to TileProvider

**Comment by kengu** [comment]
There, take two. This time with changes.

**Pull request merged**
