### PR TITLE
rotation added

### PR DESCRIPTION
**Pull request by escamoteur**
Hi, 
I added rotation functionality to the map.
Not exactly like asked in https://github.com/johnpryan/flutter_map/issues/116

Because I don't see a lot of benefit of enabling the user to rotate the map but to rotate the map from the app side e.g. connected to the compass.
So the mapController got a rotate function and the map option an initial rotation.
The rotation is done at the outmost scope so I rotate the whole map with all it's layer because it don't make sense for a single layer not to rotate.

I did not change the version, I let that to you when publishing :-)

I hope you like it.

### CODE REVIEW

**Comment by escamoteur** [comment]
Special thanks to  @slightfoot for the idea using an Overflowbox

**Comment by johnpryan** [comment]
This is really cool - thanks!

I think there's some usability issues that need to be fixed before this can be an official feature. The map jumps as you pan around when there's rotation. The tiles that are fetched for a rotated map can still lead to blank spots (as discussed in #116) since the visible area needs to take into account the rotation now.

**Comment by escamoteur** [comment]
Hi John,
I tried it here and had no such problems. The visible area does take this into account. By this:

`
        angle = degToRadian(rotation);
        final rangle90 = sin(_rad90 - angle).abs();
        final sinangle = sin(angle).abs();
        // to make sure that the whole screen is filled with the map after rotation
        // we enlarge the drawing area over the available screen size
        width = (constraints.maxWidth * rangle90) +
            (constraints.maxHeight * sinangle);
        height = (constraints.maxHeight * rangle90) +
            (constraints.maxWidth * sinangle);

        mapState.size = CustomPoint<double>(width, height);
`

**Comment by escamoteur** [comment]
Ah, I now saw what you meant with the jumping around. it has to do with the fling that isn't rotated.

**Pull request merged**
