### PR TITLE
Adding callbacks for gestures on layer elements

### PR DESCRIPTION
**Pull request by kengu**
Adds the following features for Polyline, Polygon and CircleMarker elements:

- `onTap` and `onLongPress` gesture detection
- Refactored geometry build methods
- Conversion methods from LatLng to Offset and vice-versa

### CODE REVIEW

**Comment by kengu** [comment]
@LJaraCastillo, here it the pull-request.

**Comment by LJaraCastillo** [comment]
Nice

**Comment by johnpryan** [comment]
hang tight, I'm trying to fix some merge conflicts here.

**Comment by kengu** [comment]
@johnpryan, I'll look into #174. The merge conflicts are now resolved. The code is refactored into using the `ositioned_tap_detector` package introduced by the `zoom-focal-point` pull-request.

**Comment by johnpryan** [comment]
I would like to close this and try to go with an approach like https://github.com/johnpryan/flutter_map/issues/174 that allows all layers to handle their own gesture detection. This will ultimately be the most flexible way to allow custom layers (like polygons) to decide if they've been tapped and whether or not to forward the gesture to the underlying gesture handler provided by the MapGestureMixin.

**Comment by johnpryan** [comment]
Thanks for all the feedback and pull requests, please let me know if this doesn't work for you. I've assigned #174 to myself but if you would like to take a stab at it let me know!

**Pull request closed without merging**
