### PR TITLE
#230 issue fix

### PR DESCRIPTION
**Pull request by lpongetti**
When the anchor point is out of bounds, the whole marker widget disappears

### CODE REVIEW

**Comment by lpongetti** [comment]
#230

**Comment by lpongetti** [comment]
it fix also #128 issue

**Comment by johnpryan** [comment]
thanks for the contribution!

**Comment by lpongetti** [comment]
Your welcome, please check also #312 and #306
It's very important for my plugin and project.
Thanks

**Comment by lpongetti** [comment]
Plase consider also to release 0.5.4+1 with last pull request! Thanks 😊

**Comment by johnpryan** [comment]
👍 0.5.5 is released with your changes. Let me know if you have any issues

**Comment by lpongetti** [comment]
Thanks!! 👍

**Comment by lpongetti** [comment]
Please check #317

**Pull request merged**
