### PR TITLE
Issue 290 : Add example of showing current location

### PR DESCRIPTION
**Pull request by raacker**
#290  Add example page that use [flutterlocation](https://pub.dev/packages/location) to achieve device's location and update it in live. 

* I need a confirm that upgrading sample app's requirements is okay or not. Because I had really hard time with debugging "location" library and finally got a reason why it was not running okay with flutter_map sample app.

https://pub.dev/packages/location#breaking-changes

as described on README page, location version 2 uses AndroidX and SDK 28 to run it. 

If you guys think it's too unnecessary, I might can try "location" version 1 to integrate.

I will include build.gradle commits for now.

### CODE REVIEW

**Comment by FrankenApps** [comment]
Does the map get centered again when the position changes?
Or is the first location the center of the map forever (and only the marker moves)?

**Comment by raacker** [comment]
@FrankenApps I will double check how I wrote the code but it will center to marker position if you see the code. Thanks for mentioning that.

**Comment by raacker** [comment]
@FrankenApps I will double check how I wrote the code but it will center to marker position if you see the code. Thanks for appointing that.

**Comment by johnpryan** [comment]
Thanks!

**Pull request merged**
