### PR TITLE
 added support for double-tap-hold (aka "one-finger pinch") zoom

### PR DESCRIPTION
**Pull request by avimak**
like in google maps.

### CODE REVIEW

**Comment by avimak** [comment]
`flutter rest` actually passes on my machine, not sure why did it fail on travis..

**Comment by avimak** [comment]
@johnpryan ? :)

**Comment by johnpryan** [comment]
can you update with master and run dartfmt?

**Comment by avimak** [comment]
@johnpryan , done

**Comment by avimak** [comment]
@johnpryan merged with latest changes

**Comment by avimak** [comment]
@johnpryan merged with `master` again, is there something wrong - conceptually - with this PR?

**Pull request merged**
