### PR TITLE
Support holed polygon

### LINKED ISSUE #484: Polygons with outer and inner bounds
Hi,

I try to use your plugin to display countries as a polygon overlay on open street maps. The problem is, that some countries are not a polygon in the normal way, because they enclose another country. So for that purpose, I have to use a polygone for the outer boundary and a second polygon for the inner boundary.

Is there an option to do so using the polygon class? Or is there any other way to realize this kind of overlay?

Best regards
Tobias

### PR DESCRIPTION
**Pull request by maRci002**
Hello, I made some changes to support holed polygons.

You can border holes too:
map bordered holes

Support dotted borders:
map dotted holes

Or you can disable hole borders:
map disable border around holes

Closes #484

### CODE REVIEW

**Comment by maRci002** [comment]
It seems like I broke something :laughing: I will fix soon.
map problem

**Comment by maRci002** [comment]
Managed to fix border overlay bug

max_fix_border

**Comment by maRci002** [comment]
Here is an example response to [this comment](https://github.com/johnpryan/flutter_map/issues/484#issuecomment-609182483):
holed polygon example

Code:
```
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

import '../widgets/drawer.dart';

class HomePage extends StatelessWidget {
  static const String route = '/';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Home')),
      drawer: buildDrawer(context, route),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Text('This is a map that is showing (51.5, -0.9).'),
            ),
            Flexible(
              child: FlutterMap(
                options: MapOptions(
                  center: LatLng(51.5, -0.09),
                  zoom: 16.0,
                  onTap: print,
                ),
                layers: [
                  TileLayerOptions(
                    urlTemplate:
                        'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: ['a', 'b', 'c'],
                    tileProvider: NonCachingNetworkTileProvider(),
                  ),
                  PolygonLayerOptions(
                    polygonCulling:
                        true, // just performance if polygon is out of screen then no need to render canvas
                    polygons: <Polygon>[
                      Polygon(
                        color: Colors.green.withOpacity(0.5),
                        points: [
                          LatLng(51.501903, -0.091341),
                          LatLng(51.502188, -0.087262),
                          LatLng(51.500397, -0.086404),
                          LatLng(51.499548, -0.088488),
                          LatLng(51.499756, -0.091153),
                        ],
                        holePointsList: [
                          // First hole
                          [
                            LatLng(51.501385, -0.090671),
                            LatLng(51.501639, -0.089477),
                            LatLng(51.501069, -0.089093),
                            LatLng(51.500759, -0.08969),
                            LatLng(51.500728, -0.090507),
                            LatLng(51.501176, -0.090221),
                          ],
                          // Second hole
                          [
                            LatLng(51.501145, -0.088104),
                            LatLng(51.500799, -0.08866),
                            LatLng(51.500305, -0.088251),
                            LatLng(51.500698, -0.087744),
                            LatLng(51.500784, -0.087025),
                            LatLng(51.501517, -0.087172),
                            LatLng(51.501624, -0.088006),
                          ],
                        ],
                      ),
                      // This is second Polygon so this is a multipolygon
                      Polygon(
                        color: Colors.red.withOpacity(0.5),
                        points: [
                          LatLng(51.499115, -0.092518),
                          LatLng(51.498784, -0.089543),
                          LatLng(51.497502, -0.088872),
                          LatLng(51.497186, -0.091128),
                        ],
                        holePointsList: [
                          // just one hole
                          [
                            LatLng(51.498367, -0.091513),
                            LatLng(51.498398, -0.090049),
                            LatLng(51.497828, -0.089812),
                            LatLng(51.497619, -0.090793),
                          ],
                        ],
                      ),
                      // Polygon(),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by bettdouglas** [comment]
Wagwaaan! 
Thanks for this example.

**Pull request merged**
