### PR TITLE
Wms support.

### LINKED ISSUE #225: Add bbox to templateUrl (WMS tile)
Hello, I want to add bbox to templateUrl, but can't access mapController, it's always null. 
How to do it properly?

### LINKED ISSUE #412: how to leaflet add wms layer ?

### PR DESCRIPTION
**Pull request by bugDim88**
Hello, this PR allow to use tile services that working on [WMS](https://en.wikipedia.org/wiki/Web_Map_Service) protocol. The WMS mode activated by adding `WMSTileLayerOptions` to `TileLayerOptions`, like so:
```
 TileLayerOptions(
                    wmsOptions: WMSTileLayerOptions(
                      baseUrl: 'http://maps.heigit.org/osm-wms/service?',
                      layers: ['europe_wms:hs_srtm_europa'],
                    )
                  )
```
If `wmsOptions` is not set, for building tiles urls applied standard logic.
URL building logic was applied from original [Leaflet/TileLayer.WMS.js](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.WMS.js).
Also PR contains new example page, and add `Epsg4326` crs object.

closes #412
closes #225

### CODE REVIEW

**Comment by devmgs** [comment]
Solves  #412 #225

**Comment by johnpryan** [comment]
LGTM

**Comment by klaszlo8207** [comment]
The name parameter wmsOptions is not defined :(

**Comment by bugDim88** [comment]
> The name parameter wmsOptions is not defined :(

same [issue](https://github.com/johnpryan/flutter_map/issues/512) here.  It's just not released yet.

**Pull request merged**
