### PR TITLE
Updates for incompatibilities with latest changes to flutter error handling.

### PR DESCRIPTION
**Pull request by slightfoot**
Hey @johnpryan,
Similar changes have already been made to `flutter_svg` see https://github.com/dnfield/flutter_svg/blob/master/CHANGELOG.md#0130

This is required for Flutter SDK v1.5.9 and above. I've also done a few cleanup things and bug-fixes. I've migrated the Streams for Stream<Null> to Stream<void>, although this is not a breaking change and should be compatible with external implementations of the TileOptions API. I've bumped the version to 0.6.0 according to semver.

Hit me up on Slack if you want to discuss.

### CODE REVIEW

**Comment by sjmcdowall** [comment]
@slightfoot  -- Nice work!

**Comment by johnpryan** [comment]
This is currently merged into the dev branch: https://github.com/johnpryan/flutter_map/tree/dev 

holding off to merge into master until this version of flutter hits the stable channel

**Comment by johnpryan** [comment]
the `dev` branch is published as version `0.6.0`

**Comment by johnpryan** [comment]
pieces of this have been released as part of 0.5.6 for compatibility with flutter 1.7.8 (stable) - thanks again for the help!

**Pull request closed without merging**
